# Generated by Django 3.1.1 on 2020-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Courses',
        ),
    ]
