# Generated by Django 3.1.1 on 2020-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birth', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=50)),
                ('rcmd_id', models.CharField(max_length=24, null=True)),
                ('category', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
