# Generated by Django 3.1.1 on 2020-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('isExpert', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=24)),
                ('off_name', models.CharField(max_length=30)),
                ('off_addr', models.CharField(max_length=30)),
                ('off_tel', models.CharField(max_length=30)),
                ('off_start_year', models.CharField(max_length=4)),
                ('field', models.CharField(max_length=20)),
                ('hist', models.CharField(max_length=20)),
                ('reg', models.CharField(max_length=20)),
                ('short_intro', models.CharField(max_length=100)),
                ('long_intro', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Expert',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
